// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCSteN7HKgzE_6Fq8yYg3UBAxXZVREw0',
    appId: '1:55269844611:web:b238ac576c532608411db6',
    messagingSenderId: '55269844611',
    projectId: 'fir-flutter-codelab-5f135',
    authDomain: 'fir-flutter-codelab-5f135.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5f135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugm_A8Mso3HjmLTILYrLx98DA53igeZM',
    appId: '1:55269844611:android:59634e03d4f726de411db6',
    messagingSenderId: '55269844611',
    projectId: 'fir-flutter-codelab-5f135',
    storageBucket: 'fir-flutter-codelab-5f135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sv8t2Zc8pyR6VAORitMArAPVlxqetrA',
    appId: '1:55269844611:ios:21a32a9d0aaa68ff411db6',
    messagingSenderId: '55269844611',
    projectId: 'fir-flutter-codelab-5f135',
    storageBucket: 'fir-flutter-codelab-5f135.appspot.com',
    iosClientId: '55269844611-unr7k58v00g77jbonsan5hcn3e6luaaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8sv8t2Zc8pyR6VAORitMArAPVlxqetrA',
    appId: '1:55269844611:ios:21a32a9d0aaa68ff411db6',
    messagingSenderId: '55269844611',
    projectId: 'fir-flutter-codelab-5f135',
    storageBucket: 'fir-flutter-codelab-5f135.appspot.com',
    iosClientId: '55269844611-unr7k58v00g77jbonsan5hcn3e6luaaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
